/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package info.kuonteje.voxeltest;

import org.junit.Test;
//import static org.junit.Assert.*;

public class AppTest
{
	@Test
	public void testAppHasAGreeting()
	{
		// VoxelTest classUnderTest = new VoxelTest();
		//
	}
}
